### ISSUE TITLE
Help installing on Mac

### ISSUE THREAD

**Issue by kjpete12** [MayurDivate/GUAVA#29]
I'm having problems installing GUAVA on a Mac with the most current version of R (4.0.2). This is the error I'm stuck with. Any Advice?

kathryns-MacBook-Pro:GUAVA-1 randomuser$ sh ./configure.sh
INSTALLING GUAVA-1 dependencies
>>>>>> Operating system :Mac
>>> R is already installed !
>>> R is already installed !
>>> >> > Installing R packages > >> >
[1] ">>> >> > Loading BIOCONDUCTOR > >> >>>"
Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install
Execution halted

>>> >> > Downloading miniconda2 > >> >>>
Miniconda script exists
>>> >> > GUAVA dependencies installation < << <<<
---------- Installing  miniconda ----------------
./configure.sh: line 179: /Users/randomuser/.bash_profile: No such file or directory

**Comment by MayurDivate** [comment]
Sorry for the delay. 

I have updated GUAVA and this error is resolved now.
Please download latest version.

Thank you for using GUAVA.

Mayur

**Comment by kimmaip** [comment]
Hi, I am still having this issue and I am currently using version GUAVA-1.0.1. I also cannot open the input window of GUAVA ATAC-seq data analysis program when I click on option 2 "ATAC-seq Data Analysis".  I am currently using R version 4.0.5.

**Comment by MayurDivate** [comment]
Thank you for reporting the issue.

Can you please share the output of sh ./configure.sh command?

Thanks,
Mayur

**Comment by kimmaip** [comment]
Hi Mayur!



Thanks for getting back to me. I figured out that my main error was that I did not have Anaconda 3 installed and I did not have Python 2.7 installed. However my new issue is that I cannot run GUAVA because particular dependencies (like Bowtie2) aren’t getting fully installed.



Below I have copied and pasted the output of me running the sh ./configure.sh line twice.



Kind regards,

Kimmai Phan



--
Graduate student in the Davis Lab
NSF GRFP Fellow
Wallace H. Coulter Department of Biomedical Engineering
at Georgia Institute of Technology & Emory University
Pronunciation: Kim-m-eye Fan
Pronouns: she/her


------------------------------





(py2) ***@***.*** ~ % cd ~/GUAVA-1.0.1

(py2) ***@***.*** GUAVA-1.0.1 % sh ./configure.sh

INSTALLING GUAVA-1 dependencies

>>>>>> Operating system :Mac

>>> R is already installed !

>>> R is already installed !

>>> >> > Installing R packages > >> >

dyld: Library not loaded: @rpath/./libreadline.6.2.dylib

  Referenced from: /Users/kimmaiphan/anaconda3/lib/R/lib/libR.dylib

  Reason: image not found

./configure.sh: line 96: 78994 Abort trap: 6           Rscript ./lib/InstallRequiredPackages.R



>>> CONDA is already installed !



---------- Adding BIOCONDA and other channels ----------------

Warning: 'r' already in 'channels' list, moving to the top

Warning: 'defaults' already in 'channels' list, moving to the top

Warning: 'conda-forge' already in 'channels' list, moving to the top

Warning: 'bioconda' already in 'channels' list, moving to the top





>>> >> > Installing dependencies > >> >>>

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#

>>>>> FOUND: java <<<<<

>>>>> FOUND: bedtools <<<<<

>>> >> > INSTALLING : bowtie > >> >>>

Collecting package metadata (current_repodata.json): done

Solving environment: done



## Package Plan ##



  environment location: /Users/kimmaiphan/anaconda3/envs/py2



  added / updated specs:

    - bowtie=1.1.2





The following packages will be downloaded:



    package                    |            build

    ---------------------------|-----------------

    bowtie-1.1.2               |           py27_2        1000 KB  bioconda

    ------------------------------------------------------------

                                           Total:        1000 KB



The following NEW packages will be INSTALLED:



  bowtie             bioconda/osx-64::bowtie-1.1.2-py27_2







Downloading and Extracting Packages

bowtie-1.1.2         | 1000 KB   | ##################################### | 100%

Preparing transaction: done

Verifying transaction: done

Executing transaction: done

>>> >> > INSTALLING : bowtie2 > >> >>>

Collecting package metadata (current_repodata.json): done

Solving environment: failed with initial frozen solve. Retrying with flexible solve.

Collecting package metadata (repodata.json): done

Solving environment: done



## Package Plan ##



  environment location: /Users/kimmaiphan/anaconda3/envs/py2



  added / updated specs:

    - bowtie2=2.3.2





The following packages will be downloaded:



    package                    |            build

    ---------------------------|-----------------

    bowtie2-2.3.2              |   py27pl5.22.0_1         1.3 MB  bioconda

    perl-5.22.0.1              |                0        14.6 MB  conda-forge

    tbb-2021.2.0               |       h940c156_0         146 KB  conda-forge

    ------------------------------------------------------------

                                           Total:        16.0 MB



The following NEW packages will be INSTALLED:



  bowtie2            bioconda/osx-64::bowtie2-2.3.2-py27pl5.22.0_1

  perl               conda-forge/osx-64::perl-5.22.0.1-0

  tbb                conda-forge/osx-64::tbb-2021.2.0-h940c156_0







Downloading and Extracting Packages

tbb-2021.2.0         | 146 KB    | ##################################### | 100%

perl-5.22.0.1        | 14.6 MB   | ##################################### | 100%

bowtie2-2.3.2        | 1.3 MB    | ##################################### | 100%

Preparing transaction: done

Verifying transaction: done

Executing transaction: done

>>> >> > INSTALLING : cutadapt > >> >>>

Collecting package metadata (current_repodata.json): done

Solving environment: failed with initial frozen solve. Retrying with flexible solve.

Collecting package metadata (repodata.json): done

Solving environment: done



## Package Plan ##



  environment location: /Users/kimmaiphan/anaconda3/envs/py2



  added / updated specs:

    - cutadapt=1.13





The following packages will be downloaded:



    package                    |            build

    ---------------------------|-----------------

    bz2file-0.98               |             py_0           9 KB  conda-forge

    cutadapt-1.13              |           py27_0         198 KB  bioconda

    xopen-0.7.3                |             py_0          11 KB  bioconda

    ------------------------------------------------------------

                                           Total:         218 KB



The following NEW packages will be INSTALLED:



  bz2file            conda-forge/noarch::bz2file-0.98-py_0

  cutadapt           bioconda/osx-64::cutadapt-1.13-py27_0

  xopen              bioconda/noarch::xopen-0.7.3-py_0







Downloading and Extracting Packages

bz2file-0.98         | 9 KB      | ##################################### | 100%

xopen-0.7.3          | 11 KB     | ##################################### | 100%

cutadapt-1.13        | 198 KB    | ##################################### | 100%

Preparing transaction: done

Verifying transaction: done

Executing transaction: done

>>>>> FOUND: fastqc <<<<<

>>>>> FOUND: samtools <<<<<

>>>>> FOUND: picard <<<<<

>>>>> FOUND: igv <<<<<

>>>>> FOUND: bedGraphToBigWig <<<<<

Traceback (most recent call last):

  File "<string>", line 1, in <module>

ImportError: No module named numpy



>>> >> > Installing Numpy > >> >>>

Password:

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

Collecting numpy

  Downloading numpy-1.16.6-cp27-cp27m-macosx_10_9_x86_64.whl (13.9 MB)

     |████████████████████████████████| 13.9 MB 11.0 MB/s

Installing collected packages: numpy

Successfully installed numpy-1.16.6



>>> >> > Installing MACS2 > >> >>>

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

Collecting macs2==2.1.1.20160309

  Using cached MACS2-2.1.1.20160309.tar.gz (1.6 MB)

Requirement already satisfied: numpy>=1.6 in /Users/kimmaiphan/anaconda3/envs/py2/lib/python2.7/site-packages (from macs2==2.1.1.20160309) (1.16.6)

Building wheels for collected packages: macs2

  Building wheel for macs2 (setup.py) ... done

  Created wheel for macs2: filename=MACS2-2.1.1.20160309-cp27-cp27m-macosx_10_6_x86_64.whl size=1442466 sha256=f2358ff844841280a9bc8497d80594ed6e868257f24b23ec1c865bc817685ca3

  Stored in directory: /private/var/root/Library/Caches/pip/wheels/67/0f/55/be1ea1d0db18012d7f3ed1bcfbce73b6199f2742d77359ff44

Successfully built macs2

Installing collected packages: macs2

Successfully installed macs2-2.1.1.20160309

>>>>>>>>> Finished <<<<<<<<<

(py2) ***@***.*** GUAVA-1.0.1 % java -jar GUAVA.jar

GUAVA version 1

Operating System of machine :Mac OS X

              cutadapt:            Working!

              bowtie:       Working!

              bowtie2:             NOT FOUND !!!

              fastqc:       Working!

              samtools:     Working!

              macs2:        Working!

              Picard:       Working!

              bedtools:            Working!

              bedGraphToBigWig:           Working!

              igv:          Working!



There are missing dependancies!

Please use configure.sh to install dependencies.

If you are having difficulties in installing dependencies, please report issue at *GitHub*.

>>> https://github.com/MayurDivate/GUAVASourceCode/issues

EXIT(GUAVA) ...

(py2) ***@***.*** GUAVA-1.0.1 % sh ./configure.sh

INSTALLING GUAVA-1 dependencies

>>>>>> Operating system :Mac

>>> R is already installed !

>>> R is already installed !

>>> >> > Installing R packages > >> >

dyld: Library not loaded: @rpath/./libreadline.6.2.dylib

  Referenced from: /Users/kimmaiphan/anaconda3/lib/R/lib/libR.dylib

  Reason: image not found

./configure.sh: line 96: 79414 Abort trap: 6           Rscript ./lib/InstallRequiredPackages.R



>>> CONDA is already installed !



---------- Adding BIOCONDA and other channels ----------------

Warning: 'r' already in 'channels' list, moving to the top

Warning: 'defaults' already in 'channels' list, moving to the top

Warning: 'conda-forge' already in 'channels' list, moving to the top

Warning: 'bioconda' already in 'channels' list, moving to the top





>>> >> > Installing dependencies > >> >>>

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#

>>>>> FOUND: java <<<<<

>>>>> FOUND: bedtools <<<<<

>>>>> FOUND: bowtie <<<<<

>>>>> FOUND: bowtie2 <<<<<

>>>>> FOUND: cutadapt <<<<<

>>>>> FOUND: fastqc <<<<<

>>>>> FOUND: samtools <<<<<

>>>>> FOUND: picard <<<<<

>>>>> FOUND: igv <<<<<

>>>>> FOUND: bedGraphToBigWig <<<<<







>>> MACS2 is already installed !

>>>>>>>>> Finished <<<<<<<<<

(py2) ***@***.*** GUAVA-1.0.1 % java -jar GUAVA.jar

GUAVA version 1

Closing GUAVA ...

(py2) ***@***.*** GUAVA-1.0.1 % java -jar GUAVA.jar

GUAVA version 1

Operating System of machine :Mac OS X

              cutadapt:            Working!

              bowtie:       Working!

              bowtie2:             NOT FOUND !!!

              fastqc:       Working!

              samtools:     Working!

              macs2:        Working!

              Picard:       Working!

              bedtools:            Working!

              bedGraphToBigWig:           Working!

              igv:          Working!



There are missing dependancies!

Please use configure.sh to install dependencies.

If you are having difficulties in installing dependencies, please report issue at *GitHub*.


From: Mayur Divate ***@***.***>
Reply-To: MayurDivate/GUAVA ***@***.***>
Date: Thursday, May 13, 2021 at 7:48 PM
To: MayurDivate/GUAVA ***@***.***>
Cc: "Phan, Kimmai" ***@***.***>, Comment ***@***.***>
Subject: [External] Re: [MayurDivate/GUAVA] Help installing on Mac (#29)


Thank you for reporting the issue.

Can you please share the output of sh ./configure.sh command?

Thanks,
Mayur

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMayurDivate%2FGUAVA%2Fissues%2F29%23issuecomment-840898275&data=04%7C01%7Ckimmai.phan%40emory.edu%7C718776dd299643eafea208d916698b40%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637565464831789964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1JSBrcinvFOHie60AzY9ZQl8XwWlbjyXWaaFZwDRVVE%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOBBZS6K6U6XHWJINUICELLTNRQLBANCNFSM4PUOEXYQ&data=04%7C01%7Ckimmai.phan%40emory.edu%7C718776dd299643eafea208d916698b40%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637565464831799952%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=o3u8yDhfqlrMKBmWuNLHykH85%2BMxUYq%2FwwSfLSVbdQ8%3D&reserved=0>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).
